# Generated by Django 6.0.7 on 2026-07-30 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='criada em'),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(default='BRL', max_length=3, verbose_name='moeda'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da foto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='America/Sao_Paulo', max_length=50, verbose_name='fuso horário'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='atualizada em'),
        ),
    ]
