# Generated by Django 5.2.17 on 2026-08-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pushsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='timezone',
        ),
    ]
