# Generated by Django 5.2.17 on 2026-08-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_pushsubscription_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
