# Generated by Django 6.0.7 on 2026-07-30 02:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('type', models.CharField(choices=[('stock', 'Stock'), ('bond', 'Bond'), ('real_estate', 'Real Estate'), ('mutual_fund', 'Mutual Fund'), ('etf', 'ETF')], max_length=50, verbose_name='type')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity')),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='average price')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='current price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'investment',
                'verbose_name_plural': 'investments',
                'ordering': ['-created_at'],
            },
        ),
    ]
