# Generated by Django 6.0.7 on 2026-07-30 17:13

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('type', models.CharField(choices=[('stock', 'Ação'), ('bond', 'Título'), ('real_estate', 'Imóvel'), ('mutual_fund', 'Fundo de Investimento'), ('etf', 'ETF')], max_length=50, verbose_name='tipo')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantidade')),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço médio')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço atual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'investimento',
                'verbose_name_plural': 'investimentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
