# Generated by Django 6.0.7 on 2026-07-30 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='investments', to='wallets.account', verbose_name='account'),
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='investments', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
