# Generated by Django 6.0.7 on 2026-07-30 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_initial'),
        ('wallets', '0002_alter_account_options_alter_creditcard_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-created_at'], 'verbose_name': 'investimento', 'verbose_name_plural': 'investimentos'},
        ),
        migrations.AlterField(
            model_name='investment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='investimentos', to='wallets.account', verbose_name='conta'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='average_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço médio'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço atual'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='type',
            field=models.CharField(choices=[('stock', 'Ação'), ('bond', 'Título'), ('real_estate', 'Imóvel'), ('mutual_fund', 'Fundo de Investimento'), ('etf', 'ETF')], max_length=50, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='investimentos', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
