# Generated by Django 5.2.17 on 2026-08-11 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_alter_investment_account_alter_investment_user'),
        ('wallets', '0007_account_prevent_negative_balance_on_checking_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='investment_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.CheckConstraint(condition=models.Q(('average_price__gte', 0)), name='investment_average_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.CheckConstraint(condition=models.Q(('current_price__gte', 0)), name='investment_current_price_positive'),
        ),
    ]
