# Generated by Django 6.0.7 on 2026-07-30 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0002_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='budgets', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='goaltransaction',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goal_transactions', to='planning.goal', verbose_name='objetivo'),
        ),
        migrations.AddField(
            model_name='goaltransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goal_transactions', to='transactions.transaction', verbose_name='transação'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='budget_end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='goal_end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='goaltransaction',
            constraint=models.UniqueConstraint(fields=('goal', 'transaction'), name='unique_goal_transaction_link'),
        ),
    ]
