# Generated by Django 6.0.7 on 2026-08-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_near_target_notified',
            field=models.BooleanField(default=False, verbose_name='notificado quase atingindo'),
        ),
    ]
