# Generated by Django 6.0.7 on 2026-07-30 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_initial'),
        ('transactions', '0003_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-start_date'], 'verbose_name': 'orçamento', 'verbose_name_plural': 'orçamentos'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created_at'], 'verbose_name': 'objetivo', 'verbose_name_plural': 'objetivos'},
        ),
        migrations.AlterModelOptions(
            name='goaltransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'link ao objetivo', 'verbose_name_plural': 'links aos objetivos'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='budgets', to='transactions.category', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateField(verbose_name='data de término'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateField(verbose_name='data de início'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='budgets', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor atual'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(verbose_name='data de término'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(verbose_name='data de início'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor alvo'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='goaltransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='goaltransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='goaltransaction',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='planning.goal', verbose_name='objetivo'),
        ),
        migrations.AlterField(
            model_name='goaltransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transactions.transaction', verbose_name='transação'),
        ),
        migrations.AlterField(
            model_name='goaltransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
    ]
