# Generated by Django 5.2.17 on 2026-08-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_alter_budget_category_alter_budget_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='is_warning_notified',
            field=models.BooleanField(default=False, verbose_name='notificado aviso'),
        ),
    ]
