# Generated by Django 5.2.17 on 2026-08-14 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_budget_is_warning_notified'),
        ('wallets', '0009_alter_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='wallets.account', verbose_name='conta'),
        ),
        migrations.DeleteModel(
            name='GoalTransaction',
        ),
    ]
