# Generated by Django 5.2.17 on 2026-08-24 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_goal_account_delete_goaltransaction'),
        ('transactions', '0013_remove_transaction_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'start_date', 'end_date'), name='unique_budget_period_per_user_category'),
        ),
    ]
