# Generated by Django 5.2.17 on 2026-08-28 18:27

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_budget_unique_budget_period_per_user_category'),
        ('transactions', '0015_alter_category_color_alter_tag_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='budget_end_date_after_start_date',
        ),
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_period_per_user_category',
        ),
        migrations.AddField(
            model_name='budget',
            name='is_recurring',
            field=models.BooleanField(default=True, verbose_name='recorrente mensal'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de término'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data de início'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='budget_end_date_after_start_date'),
        ),
    ]
