# Generated by Django 5.2.17 on 2026-08-31 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_alter_budget_amount_alter_goal_target_amount'),
        ('transactions', '0016_alter_recurringtransaction_amount_and_more'),
        ('wallets', '0011_alter_account_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='wallets.account', verbose_name='conta'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'is_recurring', 'start_date'], name='budget_user_rec_date_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['is_warning_notified', 'is_recurring'], name='budget_warn_notif_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', '-created_at'], name='goal_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['account'], name='goal_account_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['is_near_target_notified'], name='goal_near_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('is_recurring', True)), fields=('user', 'category'), name='unique_recurring_budget_per_user_cat'),
        ),
    ]
