# Generated by Django 5.2.17 on 2026-09-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_alter_goal_account_budget_budget_user_rec_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_completed_notified',
            field=models.BooleanField(default=False, verbose_name='notificado conclusao'),
        ),
    ]
