# Generated by Django 6.0.7 on 2026-07-30 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recurring_transactions', to='wallets.account', verbose_name='conta'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recurring_transactions', to='transactions.category', verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recurring_transactions', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='wallets.account', verbose_name='conta'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='transactions.category', verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='generated_transactions', to='transactions.recurringtransaction', verbose_name='recorrente'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='transactions.tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='in_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_in', to='transactions.transaction', verbose_name='transação de entrada'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='out_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_out', to='transactions.transaction', verbose_name='transação de saída'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transfers', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'name'), name='unique_category_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('name',), name='unique_default_category_name'),
        ),
        migrations.AddConstraint(
            model_name='recurringtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='recurringtransaction_end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_tag_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-date'], name='transaction_user_date_idx'),
        ),
    ]
