# Generated by Django 6.0.7 on 2026-08-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='transactions', to='transactions.tag', verbose_name='tags'),
        ),
    ]
