# Generated by Django 6.0.7 on 2026-07-30 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer', to='transactions.transaction', verbose_name='transação'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('transferência', 'Transferência')], max_length=15, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('transferência', 'Transferência')], max_length=15, verbose_name='tipo'),
        ),
    ]
