# Generated by Django 6.0.7 on 2026-08-08 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_tags'),
        ('wallets', '0002_account_initial_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='target_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recurring_transfers_in', to='wallets.account', verbose_name='conta de destino'),
        ),
    ]
