# Generated by Django 6.0.7 on 2026-08-09 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_recurringtransaction_target_account'),
        ('wallets', '0003_creditcardbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='wallets.creditcardbill', verbose_name='fatura'),
        ),
    ]
