# Generated by Django 6.0.7 on 2026-08-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='ignored_dates',
            field=models.JSONField(blank=True, default=list, verbose_name='datas ignoradas'),
        ),
    ]
