# Generated by Django 6.0.7 on 2026-08-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_recurringtransaction_ignored_dates'),
        ('wallets', '0005_account_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='wallets.account', verbose_name='conta'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='transactions.category', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='target_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transfers_in', to='wallets.account', verbose_name='conta de destino'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.account', verbose_name='conta'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.category', verbose_name='categoria'),
        ),
    ]
