# Generated by Django 5.2.17 on 2026-08-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_recurringtransaction_recurringtransaction_amount_positive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='categoria do sistema'),
        ),
    ]
