# Generated by Django 5.2.17 on 2026-08-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_add_is_system_to_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='due_date',
        ),
    ]
