# Generated by Django 5.2.17 on 2026-08-24 12:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_remove_transaction_due_date'),
        ('wallets', '0010_remove_creditcarddetails_available_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransactionIgnoredDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='data ignorada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
            ],
            options={
                'verbose_name': 'data ignorada de recorrência',
                'verbose_name_plural': 'datas ignoradas de recorrência',
            },
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='ignored_dates',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='transactions.category', verbose_name='categoria pai'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'active'], name='recurring_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['bill', 'status'], name='transaction_bill_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'status', '-date'], name='tx_acc_status_date_idx'),
        ),
        migrations.AddField(
            model_name='recurringtransactionignoreddate',
            name='recurring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_date_entries', to='transactions.recurringtransaction', verbose_name='transação recorrente'),
        ),
        migrations.AddIndex(
            model_name='recurringtransactionignoreddate',
            index=models.Index(fields=['recurring', 'date'], name='rec_ign_rec_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringtransactionignoreddate',
            constraint=models.UniqueConstraint(fields=('recurring', 'date'), name='unique_ignored_date_per_recurring'),
        ),
    ]
