# Generated by Django 5.2.17 on 2026-08-27 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_recurringtransactionignoreddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Insira uma cor hexadecimal válida no formato #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Insira uma cor hexadecimal válida no formato #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='cor'),
        ),
    ]
