# Generated by Django 6.0.7 on 2026-07-30 17:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('type', models.CharField(choices=[('checking', 'Conta Corrente'), ('savings', 'Conta Poupança'), ('investment', 'Investimento'), ('credit_card', 'Cartão de Crédito'), ('other', 'Outro')], max_length=50, verbose_name='tipo')),
                ('institution', models.CharField(blank=True, max_length=100, null=True, verbose_name='instituição')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='saldo')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='cor')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'conta',
                'verbose_name_plural': 'contas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CreditCardDetails',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='credit_card_details', serialize=False, to='wallets.account', verbose_name='conta')),
                ('limit', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='limite')),
                ('available_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='limite disponível')),
                ('closing_day', models.PositiveSmallIntegerField(verbose_name='dia de fechamento')),
                ('due_day', models.PositiveSmallIntegerField(verbose_name='dia de vencimento')),
            ],
            options={
                'verbose_name': 'detalhes do cartão de crédito',
                'verbose_name_plural': 'detalhes dos cartões de crédito',
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_account_name_per_user'),
        ),
    ]
