# Generated by Django 6.0.7 on 2026-08-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='saldo inicial'),
        ),
    ]
