# Generated by Django 6.0.7 on 2026-07-30 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name'], 'verbose_name': 'conta', 'verbose_name_plural': 'contas'},
        ),
        migrations.AlterModelOptions(
            name='creditcard',
            options={'ordering': ['name'], 'verbose_name': 'cartão de crédito', 'verbose_name_plural': 'cartões de crédito'},
        ),
        migrations.AlterField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True, verbose_name='ativa'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='saldo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criada em'),
        ),
        migrations.AlterField(
            model_name='account',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='instituição'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(max_length=50, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizada em'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='active',
            field=models.BooleanField(default=True, verbose_name='ativa'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='available_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='limite disponível'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='closing_day',
            field=models.PositiveSmallIntegerField(verbose_name='dia de fechamento'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criada em'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='due_day',
            field=models.PositiveSmallIntegerField(verbose_name='dia de vencimento'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='instituição'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='limite'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizada em'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='credit_cards', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
