# Generated by Django 6.0.7 on 2026-07-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_account_options_alter_creditcard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('checking', 'Conta Corrente'), ('savings', 'Conta Poupança'), ('investment', 'Investimento'), ('credit_card', 'Cartão de Crédito'), ('other', 'Outro')], max_length=50, verbose_name='tipo'),
        ),
    ]
