# Generated by Django 6.0.7 on 2026-08-09 01:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_account_initial_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_date', models.DateField(verbose_name='mês/ano da fatura')),
                ('closing_date', models.DateField(verbose_name='data de fechamento')),
                ('due_date', models.DateField(verbose_name='data de vencimento')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('closed', 'Fechada'), ('paid', 'Paga')], default='open', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='wallets.account', verbose_name='conta')),
            ],
            options={
                'verbose_name': 'fatura',
                'verbose_name_plural': 'faturas',
                'ordering': ['-period_date'],
                'constraints': [models.UniqueConstraint(fields=('account', 'period_date'), name='unique_bill_per_month')],
            },
        ),
    ]
