# Generated by Django 6.0.7 on 2026-08-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_creditcardbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardbill',
            name='is_due_tomorrow_notified',
            field=models.BooleanField(default=False, verbose_name='notificado vencimento amanha'),
        ),
    ]
