# Generated by Django 6.0.7 on 2026-08-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_creditcardbill_is_due_tomorrow_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='icon',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='ícone'),
        ),
    ]
