# Generated by Django 5.2.17 on 2026-08-11 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_alter_account_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('type', 'credit_card'), ('balance__gte', 0), _connector='OR'), name='prevent_negative_balance_on_checking_accounts'),
        ),
    ]
