# Generated by Django 5.2.17 on 2026-08-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_remove_negative_balance_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('checking', 'Conta Corrente'), ('credit_card', 'Cartão de Crédito'), ('other', 'Outro')], max_length=50, verbose_name='tipo'),
        ),
    ]
