# Generated by Django 5.2.17 on 2026-08-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0009_alter_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcarddetails',
            name='available_limit',
        ),
        migrations.AddIndex(
            model_name='creditcardbill',
            index=models.Index(fields=['account', 'status'], name='cc_bill_acc_status_idx'),
        ),
    ]
