# Generated by Django 5.2.17 on 2026-09-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0011_alter_account_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardbill',
            name='is_closed_notified',
            field=models.BooleanField(default=False, verbose_name='notificado fechamento'),
        ),
    ]
